### ISSUE TITLE
More Specific Instructions on Format of Data Dictionary Needed

### ISSUE THREAD

**Issue by bnleff** [laderast/burro#9]
I am trying to explore my own data set with burro, but am having trouble setting up a data dictionary to work. I have set up an excel sheet with two columns (one labeled variableNames containing the labels I want to show and one with the actual variable names). When running this code chunk 
```
explore_data(dataset = bnsplay, data_dictionary = data_dict)
```
the burro app loads fine, but the data dictionary does not show up. When I stop the app, the following error messages show up.
<img width="634" alt="Screen Shot 2019-08-13 at 2 24 42 PM" src="https://user-images.githubusercontent.com/48899402/62978763-e25e6980-bdd6-11e9-9cae-edd24922b76e.png">

Is there a specific way to format the excel sheet besides just a column named "variableNames" or is the problem in the way I am trying to load up the burro app entirely? Also, is the variable in the spreadsheet "variableNames" supposed to contain the existing variable names or the variable definitions? Where can I find the code for where the data dictionary is used?

**Comment by laderast** [comment]
Hi @bnleff - this appears to be a bug I introduced in the latest version. I will try and tackle it tomorrow.

The data dictionary format is flexible, it should be two columns, one with the variable name and the other one with description. I will update the documentation.

**Comment by laderast** [comment]
Hi @bnleff  - I have pushed a new version to master that addresses this. It turns out the DT package has new functions to render the output.

There is a note about the format in the `explore_data` function reference: https://laderast.github.io/burro/reference/explore_data.html

It can actually be any `data.frame` format, but I have two columns in mine: `VariableName` and `Description`. 

Please let me know if you have any other issues.
